services:
  hospital_db:
    container_name: hospital_db
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    ports:
      - 5432:5432
    networks:
      - hospital_network

  backend:
     image: dukunuu/devtools:latest
     container_name: munkhjin_backend
     volumes:
        - ./backend/:/hospital_back:cached
     working_dir: /hospital_back
     env_file:
       - ./backend/.env
     entrypoint: ["sh", "-c"]
     command: |
       "go mod download && air -c .air.toml"
     depends_on: 
       - hospital_db
     networks:
       - hospital_network
     ports:
       - 8080:8080

  flask_ml_service:
    container_name: flask_ml_service
    build:
      context: ./model
    ports: 
      - "5000:5000"
    networks:
      - hospital_network
   
  #frontend:
  #  container_name: hospital_frontend
  #  build:
  #    context: ./frontend/
  #    dockerfile: Dockerfile
  #  command: npm run dev
  #  volumes:
  #    - ./frontend:/app
  #    - app_node_modules:/app/node_modules
  #  env_file:
  #    - ./frontend/.env
  #  ports:
  #    - 5173:5173
  #  networks:
  #    - hospital_network

volumes:
  db_data:
  hospital_back:
  app_node_modules:
networks:
  hospital_network:
